channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.8.5
  - pip:
      - azureml-mlflow==1.48.0
      - azureml-defaults==1.48.0
      - ray[air]==2.8.0
      - ray-on-aml==0.2.4
      - embeddings==0.0.8
      - sentence-transformers==2.2.2
      - lxml==5.1.0
      - beautifulsoup4==4.12.2
      - langchain===0.0.343
      - faiss-cpu==1.7.4
      - faiss-gpu==1.7.2
  - pip=22.1.2
name: amlraylangchain
